####################################################################
#                                                                  #
#  Дополнительные настройки проекта для непрерывной интеграции.    #
#  В общем случае должны быть установлены в значения по умолчанию  #
#                                                                  #
####################################################################

variables:

  # может быть использована в cmake для определения того, что сборка в gitlab-ci (rocksdb.cmake)
  WCI_VERSION: "0.9.1"

  # [ON] Включить отчет о покрытии тестами (отображается в запросах на слиение)
  CODE_COVERAGE: "ON"

  # [ON] Включить расширенные опции предупреждений для всех веток
  EXTRA_WARNINGS: "ON"

  # [ON] Включить пароидальный уровень предупреждений для master
  PARANOID_WARNINGS: "ON"

  # [OFF] Сборка в статике или динамике
  BUILD_SHARED_LIBS: "OFF"

  # ./b2 --prefix=/usr/monamour/boost-static link=static threading=multi runtime-link=static install
  BOOST_ROOT: "/usr/monamour/boost-static"

  # Для сборки в динамеке указываем другой путь для boost
  #BUILD_SHARED_LIBS: "ON"
  # Установка последней версии буста:
  # ./b2 --prefix=/usr/monamour/boost-shared link=shared threading=multi runtime-link=shared install
  #BOOST_ROOT: "/usr/monamour/boost-shared"

  ROCKSDB_ROOT: "/usr/monamour/rocksdb"

  # [ON] Собирать тесты
  BUILD_TESTING: "ON"

  # [OFF] Позволить собмодулям опережать свою master-ветку
  ALLOW_AHEAD_MASTER: "OFF"

  # После успешного пуша в мастер, запустит "обновление" следующего проекта
  NEXT_PROJECT: ""

